/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  VisitRequest
} from '.././model';

import { apiClient } from '../../lib/api-client';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export const visitsCreate = (
    visitRequest: NonReadonly<VisitRequest>,
 signal?: AbortSignal
) => {
      
      
      return apiClient<VisitRequest>(
      {url: `/api/visits/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: visitRequest, signal
    },
      );
    }
  


export const getVisitsCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof visitsCreate>>, TError,{data: NonReadonly<VisitRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof visitsCreate>>, TError,{data: NonReadonly<VisitRequest>}, TContext> => {

const mutationKey = ['visitsCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof visitsCreate>>, {data: NonReadonly<VisitRequest>}> = (props) => {
          const {data} = props ?? {};

          return  visitsCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VisitsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof visitsCreate>>>
    export type VisitsCreateMutationBody = NonReadonly<VisitRequest>
    export type VisitsCreateMutationError = unknown

    export const useVisitsCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof visitsCreate>>, TError,{data: NonReadonly<VisitRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof visitsCreate>>,
        TError,
        {data: NonReadonly<VisitRequest>},
        TContext
      > => {

      const mutationOptions = getVisitsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    