/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */

export * from './newsDetail';
export * from './newsList';
export * from './newsListParams';
export * from './paginatedNewsListList';
export * from './paginatedPetListList';
export * from './petDetail';
export * from './petList';
export * from './petsListParams';
export * from './visitRequest';