/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */
import type { PetList } from './petList';

export interface PaginatedPetListList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: PetList[];
}
