/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */

export interface VisitRequest {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 20 */
  phone: string;
  /** @maxLength 254 */
  email?: string;
  message?: string;
  readonly created_at: string;
}
