/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */

export interface NewsList {
  readonly id: number;
  /** @maxLength 255 */
  title: string;
  description: string;
  image: string;
  /** @maxLength 255 */
  alt_image: string;
  date: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  views?: number;
  readonly created_at: string;
}
