/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */

export type NewsListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
};
