/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PaginatedPetListList,
  PetDetail,
  PetsListParams
} from '.././model';

import { apiClient } from '../../lib/api-client';




export const petsList = (
    params?: PetsListParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<PaginatedPetListList>(
      {url: `/api/pets/`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getPetsListQueryKey = (params?: PetsListParams,) => {
    return [
    `/api/pets/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPetsListQueryOptions = <TData = Awaited<ReturnType<typeof petsList>>, TError = unknown>(params?: PetsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPetsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof petsList>>> = ({ signal }) => petsList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof petsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type PetsListQueryResult = NonNullable<Awaited<ReturnType<typeof petsList>>>
export type PetsListQueryError = unknown


export function usePetsList<TData = Awaited<ReturnType<typeof petsList>>, TError = unknown>(
 params: undefined |  PetsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof petsList>>,
          TError,
          Awaited<ReturnType<typeof petsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function usePetsList<TData = Awaited<ReturnType<typeof petsList>>, TError = unknown>(
 params?: PetsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof petsList>>,
          TError,
          Awaited<ReturnType<typeof petsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function usePetsList<TData = Awaited<ReturnType<typeof petsList>>, TError = unknown>(
 params?: PetsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function usePetsList<TData = Awaited<ReturnType<typeof petsList>>, TError = unknown>(
 params?: PetsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getPetsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const petsRetrieve = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<PetDetail>(
      {url: `/api/pets/${id}/`, method: 'GET', signal
    },
      );
    }
  



export const getPetsRetrieveQueryKey = (id?: number,) => {
    return [
    `/api/pets/${id}/`
    ] as const;
    }

    
export const getPetsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof petsRetrieve>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsRetrieve>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPetsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof petsRetrieve>>> = ({ signal }) => petsRetrieve(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof petsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type PetsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof petsRetrieve>>>
export type PetsRetrieveQueryError = unknown


export function usePetsRetrieve<TData = Awaited<ReturnType<typeof petsRetrieve>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof petsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof petsRetrieve>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function usePetsRetrieve<TData = Awaited<ReturnType<typeof petsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof petsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof petsRetrieve>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function usePetsRetrieve<TData = Awaited<ReturnType<typeof petsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsRetrieve>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function usePetsRetrieve<TData = Awaited<ReturnType<typeof petsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petsRetrieve>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getPetsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



