import type { Metadata } from "next";
import "./globals.css";
import {ceraPro} from "@/shared/config/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en">
      <body
        className={ceraPro.variable}
      >
        {children}
      </body>
    </html>
  );
}
