/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shelter API
 * API приюта для животных
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  NewsDetail,
  NewsListParams,
  PaginatedNewsListList
} from '.././model';

import { apiClient } from '../../lib/api-client';




export const newsList = (
    params?: NewsListParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<PaginatedNewsListList>(
      {url: `/api/news/`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getNewsListQueryKey = (params?: NewsListParams,) => {
    return [
    `/api/news/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getNewsListQueryOptions = <TData = Awaited<ReturnType<typeof newsList>>, TError = unknown>(params?: NewsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNewsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof newsList>>> = ({ signal }) => newsList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof newsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type NewsListQueryResult = NonNullable<Awaited<ReturnType<typeof newsList>>>
export type NewsListQueryError = unknown


export function useNewsList<TData = Awaited<ReturnType<typeof newsList>>, TError = unknown>(
 params: undefined |  NewsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsList>>,
          TError,
          Awaited<ReturnType<typeof newsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useNewsList<TData = Awaited<ReturnType<typeof newsList>>, TError = unknown>(
 params?: NewsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsList>>,
          TError,
          Awaited<ReturnType<typeof newsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useNewsList<TData = Awaited<ReturnType<typeof newsList>>, TError = unknown>(
 params?: NewsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useNewsList<TData = Awaited<ReturnType<typeof newsList>>, TError = unknown>(
 params?: NewsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getNewsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const newsRetrieve = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<NewsDetail>(
      {url: `/api/news/${id}/`, method: 'GET', signal
    },
      );
    }
  



export const getNewsRetrieveQueryKey = (id?: number,) => {
    return [
    `/api/news/${id}/`
    ] as const;
    }

    
export const getNewsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof newsRetrieve>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsRetrieve>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNewsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof newsRetrieve>>> = ({ signal }) => newsRetrieve(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof newsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type NewsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof newsRetrieve>>>
export type NewsRetrieveQueryError = unknown


export function useNewsRetrieve<TData = Awaited<ReturnType<typeof newsRetrieve>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof newsRetrieve>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useNewsRetrieve<TData = Awaited<ReturnType<typeof newsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof newsRetrieve>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useNewsRetrieve<TData = Awaited<ReturnType<typeof newsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsRetrieve>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useNewsRetrieve<TData = Awaited<ReturnType<typeof newsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof newsRetrieve>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getNewsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



